dubbo:
  application:
    name: qf-v2-templates-web
  registry:
    address: zookeeper://192.168.122.128:2181
server:
  port: 9090
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.122.130:22122
image:
  server: http://192.168.122.130:8888
spring:
  rabbitmq:
    host: 192.168.122.137
    port: 5672
    username: rabbit
    password: 123456