dubbo:
  application:
    name: item-service-provider
  registry:
    address: zookeeper://192.168.122.128:2181
  protocol:
    port: 20984
server:
  port: 8074

spring:
  rabbitmq:
    host: 192.168.122.137
    port: 5672
    username: rabbit
    password: 123456

template:
  path: /usr/local/docker/nginx/wwwroot/item/
